<?xml version="1.0" encoding="UTF-8" ?>
<!--外部引入：<!DOCTYPE 根标签名 SYSTEM "dtd文件的位置">-->
<!DOCTYPE students SYSTEM "student.dtd">
<!--内部引入-->
<!--<!DOCTYPE students[<!ELEMENT students (student*) >
		<!ELEMENT student (name,age,sex)>
		<!ELEMENT name (#PCDATA)>
		<!ELEMENT age (#PCDATA)>
		<!ELEMENT sex (#PCDATA)>
		<!ATTLIST student number ID #REQUIRED>]>-->
<students>
	<student number="s001">
		<name>zhangsan</name>
		<age>23</age>
		<sex>male</sex>
	</student>
	<student number="s002">
		<name>lisi</name>
		<age>24</age>
		<sex>male</sex>
	</student>
</students>